# ============================================
# SITE CONFIGURATION - Replace all placeholders
# ============================================

# Business Details
business_name: "Singh's Taxi M0541"
driver_name: "Preetipal Singh"
driver_short: "Singh"
taxi_number: "M0541"
vehicle_type: "{VEHICLE_TYPE}"
abn: "{ABN}"

# Contact Information
phone_e164: "{PHONE_E164}"
phone_display: "{PHONE_DISPLAY}"
whatsapp_number: "{WHATSAPP_NUMBER}"
email_contact: "{EMAIL_CONTACT}"

# Location
city_region: "Kyneton & Surrounds"
service_areas: "Kyneton, Heathcote, Mia Mia, Redesdale"

# URLs
base_url: ""

# Map coordinates (Kyneton area)
map_lat: "-37.2467"
map_lon: "144.4542"

# Design
accent_hex: "#d4a017"

# Analytics (optional)
ga4_id: ""

# Hours
hours:
  weekdays: "By Appointment"
  weekends: "By Appointment"
  note: "Call or WhatsApp to book"
